### ISSUE TITLE
Match arm indentation for multi-line expressions

### ISSUE THREAD

**Issue by ohazi** [rust-dev-tools/fmt-rfcs#153]
There are a few instances where rustfmt produces (in my subjective opinion) less-than-ideal indentation for match arm bodies that contain expressions that are not enclosed by arm body braces. I had a brief discussion about this with some of the rustfmt developers here: https://github.com/rust-lang/rustfmt/issues/4277, and the conclusion seems to be that they're following the style guide correctly. 

Here's an example that illustrates the issue, formatted with rustfmt:
```rust
match input {
    "__focused__" => Ok(ConId::Focused),
    param => match param.starts_with("0x") {
        true => usize::from_str_radix(&param[2..], 16),
        false => param.parse(),
    }
    .map(|parsed| ConId::Id(parsed))
    .map_err(|e| format!("con_id: {}", e)),
}
```
[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0f0302f5d6d1431ea6769ffdddc996c1)

The chained calls to `map` and `map_err` are at the same indentation level as the other match arms, making it difficult to distinguish them from the match arms at a glance. 

I think it would look clearer like this:
```rust
match input {
    "__focused__" => Ok(ConId::Focused),
    param => match param.starts_with("0x") {
            true => usize::from_str_radix(&param[2..], 16),
            false => param.parse(),
        }
        .map(|parsed| ConId::Id(parsed))
        .map_err(|e| format!("con_id: {}", e)),
}
```

This example is made even more confusing if we replace the inner `match ... {}` with an `if ... {} else {}`:
```rust
match input {
    "__focused__" => Ok(ConId::Focused),
    param => if param.starts_with("0x") {
        usize::from_str_radix(&param[2..], 16)
    } else {
        param.parse()
    }
    .map(|parsed| ConId::Id(parsed))
    .map_err(|e| format!("con_id: {}", e)),
}
```
[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b1d111e43cbe3cf492f78cf6fd8bcdcb)

This match body contains only two match arms, yet four other lines are at the same indentation level. 

Again, in this case, I think it would look better like this:
```rust
match input {
    "__focused__" => Ok(ConId::Focused),
    param => if param.starts_with("0x") {
            usize::from_str_radix(&param[2..], 16)
        } else {
            param.parse()
        }
        .map(|parsed| ConId::Id(parsed))
        .map_err(|e| format!("con_id: {}", e)),
}
```

This isn't limited to brace-enclosed expressions either:
```rust
match input {
    "__focused__" => Ok(ConId::Focused),
    param => if_then_else(
        || param.starts_with("0x"),
        || usize::from_str_radix(&param[2..], 16),
        || param.parse(),
    )
    .map(|parsed| ConId::Id(parsed))
    .map_err(|e| format!("con_id: {}", e)),
}
```
[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=85226fef3a71d032838a391ec3d0269d)

I understand that this is subjective, but for me, the primary goal of match formatting should be to make it easy to identify the LHS of each arm. I don't think the current rustfmt behavior accomplishes this. 

One way to accomplish this would be to ensure that the only items that have the same indentation level as the match arms are other match arms, and possibly also a single line with terminating braces/parens/comma at the end of a match arm body. If the match arm bodies are always surrounded by body braces, then this criteria is always met:

```rust
match foo {
    bar => {
        ...
        ...
    }
    baz => {
        ...
    }
    qux => {
        ...
    }
}
```

However, there are rules about when these arm body braces should and shouldn't be used, so rustfmt will occasionally remove them if they're not needed, potentially leaving us with an issue like the one described above. 

If arm body braces are not used, but the expression begins (*and ends*) with something that kind of looks like a brace-enclosed block (e.g. another `match ... {}` or a multi-line function call), then right now you can almost just pretend that it's an arm body brace:

```rust
let _ = match "foobar" {
    "asdf" => 1,
    "fdsa" => func(
        "111111111111111111",
        "222222222222222222",
        "333333333333333333",
    ),
    param => match param.starts_with("foo") {
        true => 2,
        false => 3,
    },
    _ => unreachable!(),
};
```

The only difference is that there's a comma after the closing brace/paren (because it's an expression, not an arm body block). But visually, this looks almost identical to the example above where every arm has body braces, so it's not too bad. For the most part, I think people like this, so I don't want to propose changing the indentation here. 

But if you need to use chained method calls *after* the closing brace/paren like in the examples above -- then all of a sudden there's a whole lot of additional noise at the same indentation level, and the match arms start to get lost.

**Comment by calebcartwright** [comment]
Thanks for sharing for your perspective, but going to close because as noted in the description, it's a subjective request for something different, which doesn't justify a breaking change to the existing style specification.

You can always consider writing your code with braces on the arm bodies which would provide indentation of body content from the arm listings. We're also working on some config options within rustfmt that'll give additional options around wrapping bodies with braces
