### ISSUE TITLE
Underscores in numeric literals

### ISSUE THREAD

**Issue by varkor** [rust-dev-tools/fmt-rfcs#155]
There appears to be no guideline for underscores at the moment. Perhaps it is intended to be left to the programmer, but in particular, I think specifying whether or not underscores are encouraged between a literal and its type, e.g. `5u32` vs `5_u32` could be helpful (or specifically excluded).

**Comment by calebcartwright** [comment]
We received a similar feature request in rustfmt a couple months ago, but ultimately decided against trying to support it at that time

https://github.com/rust-lang/rustfmt/issues/3949

**Comment by joshtriplett** [comment]
On Thu, Jul 23, 2020 at 07:36:59AM -0700, varkor wrote:
> There appears to be no guideline for underscores at the moment. Perhaps it is intended to be left to the programmer, but in particular, I think specifying whether or not underscores are encouraged between a literal and its type, e.g. `5u32` vs `5_u32` could be helpful (or specifically excluded).

Underscores are available for the programmer to use or not use, at their
preference, and to the best of my knowledge, rustfmt will not change the
format you use for numeric literals.

I don't think, in general, we could provide a guideline that makes sense
for all cases. Sometimes you'd want to use `_` as a thousands separator
or a byte/word/dword separator, sometimes you'd want to use it to
separate distinct bitfields, sometimes you don't want to use it at all.

(I personally don't feel there's much value in putting an `_` between a
number and its type suffix; I find `5u32` more readable. That's a
personal opinion.)

**Comment by calebcartwright** [comment]
Closing as I agree with Josh's point about this not being applicable for inclusion within the style guide. Separately, if anyone feels strongly enough that they'd like to have the feature then I'd be receptive to reviewing a PR for rustfmt that gives the user the option.
