### ISSUE TITLE
"Line" used confusingly in rules for formatting `let` statements.

### ISSUE THREAD

**Issue by Chronos-Sk** [rust-dev-tools/fmt-rfcs#164]
The formatting rules for `let` statements uses inconsistent meaning for the word "line", to the point where I get lost trying to understand what some of the rules even mean:

> If the first line does not fit on a single line, then split after the colon,
using block indentation. If the type covers multiple lines, even after line-
breaking after the `:`, then the first line may be placed on the same line as
the `:`, subject to the [combining rules](https://github.com/rust-lang-nursery/fmt-rfcs/issues/61) (WIP).

[Statements.md](https://github.com/rust-dev-tools/fmt-rfcs/blob/215291ef72823ae3a6adfad9b26334bed6707a13/guide/statements.md)

There should probably be distinct terminology for a logical line and a formatted line. Or, at least, there should be more disambiguation.

**Comment by calebcartwright** [comment]
Thanks for sharing. Would you mind expanding on your description to help me better understand your perspective? For example, you've introduced phrases "logical line" that aren't part of the Style Guide, and it's not clear what that phrase means to you. Additionally, I'm unclear what aspect(s) of the formatting rules for the statement you've linked to you find confusing.

Remember that there is a contiguous, sequential theme to many of the codified rules that just happen to have code snippets to provide a visual representation as the rules are provided.
Specifically with the text you've quoted (`if the first line does not fit on a single line`) this is a continuation of the immediately preceding text describing a scenario where the entire statement cannot fit on one line, and so would be split after the assignment operator, e.g.

```rust
let pattern: Type =
    expr;
```

but it goes a step further to describe what to do next after applying that split in case the remaining first line (`let pattern: Type =`) itself still cannot fit on one line, namely moving the type portion around.

**Comment by calebcartwright** [comment]
Feel free to add a follow up comment, but I think given the above it makes sense to close this issue.
